### ISSUE TITLE
Add option or alternative to `instance.receive` to return the first message on any slot of a vector port

### ISSUE THREAD

**Issue by maarten-ic** [multiscale/muscle3#178] opened 2023-01-31 12:53 UTC
This would be useful for load-balancing: when distributing work on a vector port, some instances may be finished earlier than others. `receive_any` would return the first message sent to any slot of the vector port.

**Comment by LourensVeen** [comment] 2023-02-19 11:01
Duplicate of #79. Yes, it's been on the planning for *that* long :).

**Closed by LourensVeen** 2023-02-19 11:01 UTC
Labels: enhancement
