### ISSUE TITLE
Specialization of instance.get_setting_as for int would be nice

### ISSUE THREAD

**Issue by diregoblin** [multiscale/muscle3#55] opened 2020-05-12 13:02 UTC
Currently, we have ``instance.get_setting_as<int64_t>``, which is called ``long`` on most 64-bit architectures. 

For most integer parameters used in the C++ models, people likely use ``int`` (I know I do :) ). In LP64, ``int`` is 32 bits, which causes an error if you try to call ``instance.get_setting_as<int>`` - you have to either use ``<long>`` or ``<int64_t>``. Specifying the template for ``int32_t`` should solve it.

**Comment by LourensVeen** [comment] 2020-05-12 13:39
Ah yes, technically you can have a double precision float or a long int for the numbers, and I disabled single precision float and 32-bit int to avoid accidental precision loss or overflow. You're of course completely right that that is the computer scientist way of thinking, and that MUSCLE 3 is intended to be a tool for normal people :-). Especially since most numbers are 0 or 1 anyway :-).

I'll add those specialisations, and I'll add an overflow check for the `int32_t` one just because I can. Not much to be done for the precision loss I guess, so that will have to be for the user to check.

**Comment by LourensVeen** [comment] 2020-05-22 11:05
I'm thinking about this again. The problem isn't that you can't assign the value you get to an `int`. You can write `int x = instance.get_setting_as<int64_t>("setting");` just fine, it won't even give a warning. It may silently overflow, but that is standard C++ behaviour, and the line clearly states both types, so that it should be obvious that this can happen. In contrast, if I implement `get_setting_as<int>()`, then it's not obvious from the source code that there is a conversion, so now if there's an overflow you can't see what's causing it. And that is bad.

In the YAML file, you can write 64-bit numbers, and that is what is stored in the `Settings` object. No 32-bit value is ever stored, even if the number is small enough to fit in one. So the above is consistent, and it's not wrong.

On the other hand, if the user is not an experienced C++ programmer, then they may have never heard of `int64_t`, nor know what it means. All they may know is that the model they're porting has an `int` variable and they want to get the value from MUSCLE. In that case, it's probably better if they can just write `get_settings_as<int>()`, but *only* if that checks the value and throws if it doesn't fit in an `int`. So let's do it that way.

**Comment by LourensVeen** [comment] 2020-09-30 09:28
Released with 0.3.2.

**Closed by LourensVeen** 2020-09-30 09:28 UTC
Labels: enhancement, ready for release
